name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: pwd
      - run: ls -l
      - run: docker build -t test-cookiecutter-ansible . -f test/Dockerfile
      - run: docker run test-cookiecutter-ansible

